### ISSUE TITLE
Tests fail on JDK 12

### ISSUE THREAD

**Issue by SethTisue** [playframework/play-file-watch#46]
This turned up in the Scala 2.12 community build, running on JDK 12.

It's also easily reproducible outside dbuild, just fire up sbt and run `test`. The result is:

```
[info] JNotifyFileWatchServiceSpec
[info] 
[info] The file watch service should
[error]   ! detect new files
[error]    java.lang.NoSuchFieldException: sys_paths (JNotifyFileWatchService.scala:102)
[error] play.dev.filewatch.JNotifyFileWatchService$.$anonfun$apply$2(JNotifyFileWatchService.scala:102)
[error] play.dev.filewatch.JNotifyFileWatchService$.$anonfun$apply$1(JNotifyFileWatchService.scala:75)
[error] play.dev.filewatch.JNotifyFileWatchService$.apply(JNotifyFileWatchService.scala:73)
[error] play.dev.filewatch.FileWatchService$.jnotify(FileWatchService.scala:92)
[error] play.dev.filewatch.JNotifyFileWatchServiceSpec.watchService(FileWatchServiceSpec.scala:25)
[error] play.dev.filewatch.FileWatchServiceSpec.watchFiles(FileWatchServiceSpec.scala:85)
[error] play.dev.filewatch.FileWatchServiceSpec.$anonfun$new$5(FileWatchServiceSpec.scala:97)
[error] play.dev.filewatch.FileWatchServiceSpec.withTempDir(FileWatchServiceSpec.scala:51)
[error] play.dev.filewatch.FileWatchServiceSpec.$anonfun$new$4(FileWatchServiceSpec.scala:96)
```

**Comment by renatocaval** [comment]
@SethTisue, thanks for reporting.

We are not yet focusing on JDK12 build so I'm putting this on the backlog for after 2.8.0 release.

**Comment by renatocaval** [comment]
By 2.8.0 release, I mean Play 2.8.0. Not play-file-watch.

**Comment by SethTisue** [comment]
okay, I can just exclude the test in the community build for now.

**Comment by marcospereira** [comment]
So, this requires some investigation, but I think the way to go here is to remove JNotify. It is outdated and I don't think a lot of people are using it.

**Comment by mkurz** [comment]
This is the code that fails:
https://github.com/playframework/play-file-watch/blob/84503e432d65d45b07bfb153a4601f858071e9cf/src/main/scala/play/dev/filewatch/JNotifyFileWatchService.scala#L122-L124
`sys_paths` [can be found here](https://github.com/openjdk/jdk/blob/jdk9-b94/jdk/src/java.base/share/classes/java/lang/ClassLoader.java#L1755).
Starting with Java 12 however the JDK prevent all reflective access to fields in `java.lang.ClassLoader`... See
- https://stackoverflow.com/questions/56039341/get-declared-fields-of-java-lang-reflect-fields-in-jdk12
- https://bugs.openjdk.java.net/browse/JDK-8210522

Like described in the above stackoverflow answer there is a workaround using `MethodHandles.privateLookupIn` (also see this [sof answer.](https://stackoverflow.com/a/59468135/810109)). However the `privateLookupIn` method [is only available starting with Java 9](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/invoke/MethodHandles.html#privateLookupIn(java.lang.Class,java.lang.invoke.MethodHandles.Lookup)), we are still on Java 8...

Now... It turns out that in Java 15 the `sys_path` field [does not even exist anymore in `java.lang.ClassLoader`.](https://github.com/openjdk/jdk/blob/jdk-15%2B34/src/java.base/share/classes/java/lang/ClassLoader.java)... It [was moved to `jdk.internal.loader.NativeLibraries`](https://github.com/openjdk/jdk/commit/d5d6dc0caa1d2db6e85b3fe979ae7a204678de57#diff-adb19e1ee909ed1564a1a21ae61580226e4b5dd3154a53fbf613f6660b56d013): [`static final String[] SYS_PATHS`](https://github.com/openjdk/jdk/blob/jdk-15%2B34/src/java.base/share/classes/jdk/internal/loader/NativeLibraries.java#L440)

<hr>

Anyway... I agree with @marcospereira, let's just remove JNotify - it has no real use anymore. It [was introduced](https://github.com/playframework/playframework/commit/e170e85b968e71d5ac0370dd4faec36faa57ad01#diff-ec261f75c247d15b297e3af41ce5cce377993dd908d940589aad865c47637058R301) in Play 2.1 in 2012 when Play still supported Java 6 and it was needed back then. Even Play 2.3 still had support for Java 6, so it had its usage until Play 2.4 in 2015 when Java 8 was required for Play, which means the Java 7 Standard API for file watching could be relied on: https://www.playframework.com/changelog

**Comment by mkurz** [comment]
Pull request to remove JNotify: #119
